// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sink-message.proto

package org.opennms.core.ipc.grpc.common;

public final class SinkMessageProtos {
  private SinkMessageProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SinkMessageProto_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SinkMessageProto_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SinkMessageProto_TracingInfoEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SinkMessageProto_TracingInfoEntry_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\022sink-message.proto\"\331\001\n\020SinkMessageProt" +
      "o\022\022\n\nmessage_id\030\001 \001(\t\022\017\n\007content\030\002 \001(\014\022\034" +
      "\n\024current_chunk_number\030\005 \001(\005\022\024\n\014total_ch" +
      "unks\030\006 \001(\005\0228\n\014tracing_info\030\007 \003(\0132\".SinkM" +
      "essageProto.TracingInfoEntry\0322\n\020TracingI" +
      "nfoEntry\022\013\n\003key\030\001 \001(\t\022\r\n\005value\030\002 \001(\t:\0028\001" +
      "B6\n\037org.opennms.core.ipc.sink.modelB\021Sin" +
      "kMessageProtosP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_SinkMessageProto_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_SinkMessageProto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SinkMessageProto_descriptor,
        new String[] { "MessageId", "Content", "CurrentChunkNumber", "TotalChunks", "TracingInfo", });
    internal_static_SinkMessageProto_TracingInfoEntry_descriptor =
      internal_static_SinkMessageProto_descriptor.getNestedTypes().get(0);
    internal_static_SinkMessageProto_TracingInfoEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SinkMessageProto_TracingInfoEntry_descriptor,
        new String[] { "Key", "Value", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
