// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ipc.proto

package org.opennms.core.ipc.grpc.common;

public interface SinkMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:SinkMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string message_id = 1;</code>
   */
  java.lang.String getMessageId();
  /**
   * <code>string message_id = 1;</code>
   */
  com.google.protobuf.ByteString
      getMessageIdBytes();

  /**
   * <code>bytes content = 2;</code>
   */
  com.google.protobuf.ByteString getContent();

  /**
   * <code>string system_id = 3;</code>
   */
  java.lang.String getSystemId();
  /**
   * <code>string system_id = 3;</code>
   */
  com.google.protobuf.ByteString
      getSystemIdBytes();

  /**
   * <code>string location = 4;</code>
   */
  java.lang.String getLocation();
  /**
   * <code>string location = 4;</code>
   */
  com.google.protobuf.ByteString
      getLocationBytes();

  /**
   * <code>string module_id = 5;</code>
   */
  java.lang.String getModuleId();
  /**
   * <code>string module_id = 5;</code>
   */
  com.google.protobuf.ByteString
      getModuleIdBytes();

  /**
   * <code>map&lt;string, string&gt; tracing_info = 6;</code>
   */
  int getTracingInfoCount();
  /**
   * <code>map&lt;string, string&gt; tracing_info = 6;</code>
   */
  boolean containsTracingInfo(
      java.lang.String key);
  /**
   * Use {@link #getTracingInfoMap()} instead.
   */
  @java.lang.Deprecated
  java.util.Map<java.lang.String, java.lang.String>
  getTracingInfo();
  /**
   * <code>map&lt;string, string&gt; tracing_info = 6;</code>
   */
  java.util.Map<java.lang.String, java.lang.String>
  getTracingInfoMap();
  /**
   * <code>map&lt;string, string&gt; tracing_info = 6;</code>
   */

  java.lang.String getTracingInfoOrDefault(
      java.lang.String key,
      java.lang.String defaultValue);
  /**
   * <code>map&lt;string, string&gt; tracing_info = 6;</code>
   */

  java.lang.String getTracingInfoOrThrow(
      java.lang.String key);
}
