// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sink-message.proto

package org.opennms.core.ipc.grpc.common;

public interface SinkMessageProtoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:SinkMessageProto)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string message_id = 1;</code>
   */
  String getMessageId();
  /**
   * <code>string message_id = 1;</code>
   */
  com.google.protobuf.ByteString
      getMessageIdBytes();

  /**
   * <code>bytes content = 2;</code>
   */
  com.google.protobuf.ByteString getContent();

  /**
   * <code>int32 current_chunk_number = 5;</code>
   */
  int getCurrentChunkNumber();

  /**
   * <code>int32 total_chunks = 6;</code>
   */
  int getTotalChunks();

  /**
   * <code>map&lt;string, string&gt; tracing_info = 7;</code>
   */
  int getTracingInfoCount();
  /**
   * <code>map&lt;string, string&gt; tracing_info = 7;</code>
   */
  boolean containsTracingInfo(
          String key);
  /**
   * Use {@link #getTracingInfoMap()} instead.
   */
  @Deprecated
  java.util.Map<String, String>
  getTracingInfo();
  /**
   * <code>map&lt;string, string&gt; tracing_info = 7;</code>
   */
  java.util.Map<String, String>
  getTracingInfoMap();
  /**
   * <code>map&lt;string, string&gt; tracing_info = 7;</code>
   */

  String getTracingInfoOrDefault(
          String key,
          String defaultValue);
  /**
   * <code>map&lt;string, string&gt; tracing_info = 7;</code>
   */

  String getTracingInfoOrThrow(
          String key);
}
