// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sink-message.proto

package org.opennms.core.ipc.grpc.common;

public final class SinkMessageProtos {
  private SinkMessageProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface TracingInfoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:TracingInfo)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string key = 1;</code>
     */
    boolean hasKey();
    /**
     * <code>required string key = 1;</code>
     */
    java.lang.String getKey();
    /**
     * <code>required string key = 1;</code>
     */
    com.google.protobuf.ByteString
        getKeyBytes();

    /**
     * <code>required string value = 2;</code>
     */
    boolean hasValue();
    /**
     * <code>required string value = 2;</code>
     */
    java.lang.String getValue();
    /**
     * <code>required string value = 2;</code>
     */
    com.google.protobuf.ByteString
        getValueBytes();
  }
  /**
   * Protobuf type {@code TracingInfo}
   */
  public  static final class TracingInfo extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:TracingInfo)
      TracingInfoOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use TracingInfo.newBuilder() to construct.
    private TracingInfo(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private TracingInfo() {
      key_ = "";
      value_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private TracingInfo(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              key_ = bs;
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              value_ = bs;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.opennms.core.ipc.grpc.common.SinkMessageProtos.internal_static_TracingInfo_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.opennms.core.ipc.grpc.common.SinkMessageProtos.internal_static_TracingInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.opennms.core.ipc.grpc.common.SinkMessageProtos.TracingInfo.class, org.opennms.core.ipc.grpc.common.SinkMessageProtos.TracingInfo.Builder.class);
    }

    private int bitField0_;
    public static final int KEY_FIELD_NUMBER = 1;
    private volatile java.lang.Object key_;
    /**
     * <code>required string key = 1;</code>
     */
    public boolean hasKey() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string key = 1;</code>
     */
    public java.lang.String getKey() {
      java.lang.Object ref = key_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          key_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string key = 1;</code>
     */
    public com.google.protobuf.ByteString
        getKeyBytes() {
      java.lang.Object ref = key_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        key_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int VALUE_FIELD_NUMBER = 2;
    private volatile java.lang.Object value_;
    /**
     * <code>required string value = 2;</code>
     */
    public boolean hasValue() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string value = 2;</code>
     */
    public java.lang.String getValue() {
      java.lang.Object ref = value_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          value_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string value = 2;</code>
     */
    public com.google.protobuf.ByteString
        getValueBytes() {
      java.lang.Object ref = value_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        value_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasKey()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasValue()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, key_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, value_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, key_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, value_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.opennms.core.ipc.grpc.common.SinkMessageProtos.TracingInfo)) {
        return super.equals(obj);
      }
      org.opennms.core.ipc.grpc.common.SinkMessageProtos.TracingInfo other = (org.opennms.core.ipc.grpc.common.SinkMessageProtos.TracingInfo) obj;

      boolean result = true;
      result = result && (hasKey() == other.hasKey());
      if (hasKey()) {
        result = result && getKey()
            .equals(other.getKey());
      }
      result = result && (hasValue() == other.hasValue());
      if (hasValue()) {
        result = result && getValue()
            .equals(other.getValue());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasKey()) {
        hash = (37 * hash) + KEY_FIELD_NUMBER;
        hash = (53 * hash) + getKey().hashCode();
      }
      if (hasValue()) {
        hash = (37 * hash) + VALUE_FIELD_NUMBER;
        hash = (53 * hash) + getValue().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.opennms.core.ipc.grpc.common.SinkMessageProtos.TracingInfo parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.opennms.core.ipc.grpc.common.SinkMessageProtos.TracingInfo parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.opennms.core.ipc.grpc.common.SinkMessageProtos.TracingInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.opennms.core.ipc.grpc.common.SinkMessageProtos.TracingInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.opennms.core.ipc.grpc.common.SinkMessageProtos.TracingInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.opennms.core.ipc.grpc.common.SinkMessageProtos.TracingInfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.opennms.core.ipc.grpc.common.SinkMessageProtos.TracingInfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.opennms.core.ipc.grpc.common.SinkMessageProtos.TracingInfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.opennms.core.ipc.grpc.common.SinkMessageProtos.TracingInfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static org.opennms.core.ipc.grpc.common.SinkMessageProtos.TracingInfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.opennms.core.ipc.grpc.common.SinkMessageProtos.TracingInfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.opennms.core.ipc.grpc.common.SinkMessageProtos.TracingInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.opennms.core.ipc.grpc.common.SinkMessageProtos.TracingInfo prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code TracingInfo}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:TracingInfo)
        org.opennms.core.ipc.grpc.common.SinkMessageProtos.TracingInfoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.opennms.core.ipc.grpc.common.SinkMessageProtos.internal_static_TracingInfo_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.opennms.core.ipc.grpc.common.SinkMessageProtos.internal_static_TracingInfo_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.opennms.core.ipc.grpc.common.SinkMessageProtos.TracingInfo.class, org.opennms.core.ipc.grpc.common.SinkMessageProtos.TracingInfo.Builder.class);
      }

      // Construct using org.opennms.core.ipc.grpc.common.SinkMessageProtos.TracingInfo.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        key_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        value_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.opennms.core.ipc.grpc.common.SinkMessageProtos.internal_static_TracingInfo_descriptor;
      }

      @java.lang.Override
      public org.opennms.core.ipc.grpc.common.SinkMessageProtos.TracingInfo getDefaultInstanceForType() {
        return org.opennms.core.ipc.grpc.common.SinkMessageProtos.TracingInfo.getDefaultInstance();
      }

      @java.lang.Override
      public org.opennms.core.ipc.grpc.common.SinkMessageProtos.TracingInfo build() {
        org.opennms.core.ipc.grpc.common.SinkMessageProtos.TracingInfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public org.opennms.core.ipc.grpc.common.SinkMessageProtos.TracingInfo buildPartial() {
        org.opennms.core.ipc.grpc.common.SinkMessageProtos.TracingInfo result = new org.opennms.core.ipc.grpc.common.SinkMessageProtos.TracingInfo(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.key_ = key_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.value_ = value_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.opennms.core.ipc.grpc.common.SinkMessageProtos.TracingInfo) {
          return mergeFrom((org.opennms.core.ipc.grpc.common.SinkMessageProtos.TracingInfo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.opennms.core.ipc.grpc.common.SinkMessageProtos.TracingInfo other) {
        if (other == org.opennms.core.ipc.grpc.common.SinkMessageProtos.TracingInfo.getDefaultInstance()) return this;
        if (other.hasKey()) {
          bitField0_ |= 0x00000001;
          key_ = other.key_;
          onChanged();
        }
        if (other.hasValue()) {
          bitField0_ |= 0x00000002;
          value_ = other.value_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        if (!hasKey()) {
          return false;
        }
        if (!hasValue()) {
          return false;
        }
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.opennms.core.ipc.grpc.common.SinkMessageProtos.TracingInfo parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.opennms.core.ipc.grpc.common.SinkMessageProtos.TracingInfo) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object key_ = "";
      /**
       * <code>required string key = 1;</code>
       */
      public boolean hasKey() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string key = 1;</code>
       */
      public java.lang.String getKey() {
        java.lang.Object ref = key_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            key_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string key = 1;</code>
       */
      public com.google.protobuf.ByteString
          getKeyBytes() {
        java.lang.Object ref = key_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          key_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string key = 1;</code>
       */
      public Builder setKey(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        key_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string key = 1;</code>
       */
      public Builder clearKey() {
        bitField0_ = (bitField0_ & ~0x00000001);
        key_ = getDefaultInstance().getKey();
        onChanged();
        return this;
      }
      /**
       * <code>required string key = 1;</code>
       */
      public Builder setKeyBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        key_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object value_ = "";
      /**
       * <code>required string value = 2;</code>
       */
      public boolean hasValue() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string value = 2;</code>
       */
      public java.lang.String getValue() {
        java.lang.Object ref = value_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            value_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string value = 2;</code>
       */
      public com.google.protobuf.ByteString
          getValueBytes() {
        java.lang.Object ref = value_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          value_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string value = 2;</code>
       */
      public Builder setValue(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        value_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string value = 2;</code>
       */
      public Builder clearValue() {
        bitField0_ = (bitField0_ & ~0x00000002);
        value_ = getDefaultInstance().getValue();
        onChanged();
        return this;
      }
      /**
       * <code>required string value = 2;</code>
       */
      public Builder setValueBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        value_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:TracingInfo)
    }

    // @@protoc_insertion_point(class_scope:TracingInfo)
    private static final org.opennms.core.ipc.grpc.common.SinkMessageProtos.TracingInfo DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.opennms.core.ipc.grpc.common.SinkMessageProtos.TracingInfo();
    }

    public static org.opennms.core.ipc.grpc.common.SinkMessageProtos.TracingInfo getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<TracingInfo>
        PARSER = new com.google.protobuf.AbstractParser<TracingInfo>() {
      @java.lang.Override
      public TracingInfo parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new TracingInfo(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<TracingInfo> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<TracingInfo> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public org.opennms.core.ipc.grpc.common.SinkMessageProtos.TracingInfo getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface SinkMessageProtoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:SinkMessageProto)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string message_id = 1;</code>
     */
    boolean hasMessageId();
    /**
     * <code>required string message_id = 1;</code>
     */
    java.lang.String getMessageId();
    /**
     * <code>required string message_id = 1;</code>
     */
    com.google.protobuf.ByteString
        getMessageIdBytes();

    /**
     * <code>required bytes content = 2;</code>
     */
    boolean hasContent();
    /**
     * <code>required bytes content = 2;</code>
     */
    com.google.protobuf.ByteString getContent();

    /**
     * <code>optional int32 current_chunk_number = 5;</code>
     */
    boolean hasCurrentChunkNumber();
    /**
     * <code>optional int32 current_chunk_number = 5;</code>
     */
    int getCurrentChunkNumber();

    /**
     * <code>optional int32 total_chunks = 6;</code>
     */
    boolean hasTotalChunks();
    /**
     * <code>optional int32 total_chunks = 6;</code>
     */
    int getTotalChunks();

    /**
     * <code>repeated .TracingInfo tracing_info = 7;</code>
     */
    java.util.List<org.opennms.core.ipc.grpc.common.SinkMessageProtos.TracingInfo> 
        getTracingInfoList();
    /**
     * <code>repeated .TracingInfo tracing_info = 7;</code>
     */
    org.opennms.core.ipc.grpc.common.SinkMessageProtos.TracingInfo getTracingInfo(int index);
    /**
     * <code>repeated .TracingInfo tracing_info = 7;</code>
     */
    int getTracingInfoCount();
    /**
     * <code>repeated .TracingInfo tracing_info = 7;</code>
     */
    java.util.List<? extends org.opennms.core.ipc.grpc.common.SinkMessageProtos.TracingInfoOrBuilder> 
        getTracingInfoOrBuilderList();
    /**
     * <code>repeated .TracingInfo tracing_info = 7;</code>
     */
    org.opennms.core.ipc.grpc.common.SinkMessageProtos.TracingInfoOrBuilder getTracingInfoOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code SinkMessageProto}
   */
  public  static final class SinkMessageProto extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:SinkMessageProto)
      SinkMessageProtoOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use SinkMessageProto.newBuilder() to construct.
    private SinkMessageProto(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private SinkMessageProto() {
      messageId_ = "";
      content_ = com.google.protobuf.ByteString.EMPTY;
      currentChunkNumber_ = 0;
      totalChunks_ = 0;
      tracingInfo_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private SinkMessageProto(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              messageId_ = bs;
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              content_ = input.readBytes();
              break;
            }
            case 40: {
              bitField0_ |= 0x00000004;
              currentChunkNumber_ = input.readInt32();
              break;
            }
            case 48: {
              bitField0_ |= 0x00000008;
              totalChunks_ = input.readInt32();
              break;
            }
            case 58: {
              if (!((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
                tracingInfo_ = new java.util.ArrayList<org.opennms.core.ipc.grpc.common.SinkMessageProtos.TracingInfo>();
                mutable_bitField0_ |= 0x00000010;
              }
              tracingInfo_.add(
                  input.readMessage(org.opennms.core.ipc.grpc.common.SinkMessageProtos.TracingInfo.PARSER, extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
          tracingInfo_ = java.util.Collections.unmodifiableList(tracingInfo_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.opennms.core.ipc.grpc.common.SinkMessageProtos.internal_static_SinkMessageProto_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.opennms.core.ipc.grpc.common.SinkMessageProtos.internal_static_SinkMessageProto_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.opennms.core.ipc.grpc.common.SinkMessageProtos.SinkMessageProto.class, org.opennms.core.ipc.grpc.common.SinkMessageProtos.SinkMessageProto.Builder.class);
    }

    private int bitField0_;
    public static final int MESSAGE_ID_FIELD_NUMBER = 1;
    private volatile java.lang.Object messageId_;
    /**
     * <code>required string message_id = 1;</code>
     */
    public boolean hasMessageId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string message_id = 1;</code>
     */
    public java.lang.String getMessageId() {
      java.lang.Object ref = messageId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          messageId_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string message_id = 1;</code>
     */
    public com.google.protobuf.ByteString
        getMessageIdBytes() {
      java.lang.Object ref = messageId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        messageId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CONTENT_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString content_;
    /**
     * <code>required bytes content = 2;</code>
     */
    public boolean hasContent() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required bytes content = 2;</code>
     */
    public com.google.protobuf.ByteString getContent() {
      return content_;
    }

    public static final int CURRENT_CHUNK_NUMBER_FIELD_NUMBER = 5;
    private int currentChunkNumber_;
    /**
     * <code>optional int32 current_chunk_number = 5;</code>
     */
    public boolean hasCurrentChunkNumber() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional int32 current_chunk_number = 5;</code>
     */
    public int getCurrentChunkNumber() {
      return currentChunkNumber_;
    }

    public static final int TOTAL_CHUNKS_FIELD_NUMBER = 6;
    private int totalChunks_;
    /**
     * <code>optional int32 total_chunks = 6;</code>
     */
    public boolean hasTotalChunks() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional int32 total_chunks = 6;</code>
     */
    public int getTotalChunks() {
      return totalChunks_;
    }

    public static final int TRACING_INFO_FIELD_NUMBER = 7;
    private java.util.List<org.opennms.core.ipc.grpc.common.SinkMessageProtos.TracingInfo> tracingInfo_;
    /**
     * <code>repeated .TracingInfo tracing_info = 7;</code>
     */
    public java.util.List<org.opennms.core.ipc.grpc.common.SinkMessageProtos.TracingInfo> getTracingInfoList() {
      return tracingInfo_;
    }
    /**
     * <code>repeated .TracingInfo tracing_info = 7;</code>
     */
    public java.util.List<? extends org.opennms.core.ipc.grpc.common.SinkMessageProtos.TracingInfoOrBuilder> 
        getTracingInfoOrBuilderList() {
      return tracingInfo_;
    }
    /**
     * <code>repeated .TracingInfo tracing_info = 7;</code>
     */
    public int getTracingInfoCount() {
      return tracingInfo_.size();
    }
    /**
     * <code>repeated .TracingInfo tracing_info = 7;</code>
     */
    public org.opennms.core.ipc.grpc.common.SinkMessageProtos.TracingInfo getTracingInfo(int index) {
      return tracingInfo_.get(index);
    }
    /**
     * <code>repeated .TracingInfo tracing_info = 7;</code>
     */
    public org.opennms.core.ipc.grpc.common.SinkMessageProtos.TracingInfoOrBuilder getTracingInfoOrBuilder(
        int index) {
      return tracingInfo_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasMessageId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasContent()) {
        memoizedIsInitialized = 0;
        return false;
      }
      for (int i = 0; i < getTracingInfoCount(); i++) {
        if (!getTracingInfo(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, messageId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, content_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(5, currentChunkNumber_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt32(6, totalChunks_);
      }
      for (int i = 0; i < tracingInfo_.size(); i++) {
        output.writeMessage(7, tracingInfo_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, messageId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, content_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, currentChunkNumber_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(6, totalChunks_);
      }
      for (int i = 0; i < tracingInfo_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(7, tracingInfo_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.opennms.core.ipc.grpc.common.SinkMessageProtos.SinkMessageProto)) {
        return super.equals(obj);
      }
      org.opennms.core.ipc.grpc.common.SinkMessageProtos.SinkMessageProto other = (org.opennms.core.ipc.grpc.common.SinkMessageProtos.SinkMessageProto) obj;

      boolean result = true;
      result = result && (hasMessageId() == other.hasMessageId());
      if (hasMessageId()) {
        result = result && getMessageId()
            .equals(other.getMessageId());
      }
      result = result && (hasContent() == other.hasContent());
      if (hasContent()) {
        result = result && getContent()
            .equals(other.getContent());
      }
      result = result && (hasCurrentChunkNumber() == other.hasCurrentChunkNumber());
      if (hasCurrentChunkNumber()) {
        result = result && (getCurrentChunkNumber()
            == other.getCurrentChunkNumber());
      }
      result = result && (hasTotalChunks() == other.hasTotalChunks());
      if (hasTotalChunks()) {
        result = result && (getTotalChunks()
            == other.getTotalChunks());
      }
      result = result && getTracingInfoList()
          .equals(other.getTracingInfoList());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasMessageId()) {
        hash = (37 * hash) + MESSAGE_ID_FIELD_NUMBER;
        hash = (53 * hash) + getMessageId().hashCode();
      }
      if (hasContent()) {
        hash = (37 * hash) + CONTENT_FIELD_NUMBER;
        hash = (53 * hash) + getContent().hashCode();
      }
      if (hasCurrentChunkNumber()) {
        hash = (37 * hash) + CURRENT_CHUNK_NUMBER_FIELD_NUMBER;
        hash = (53 * hash) + getCurrentChunkNumber();
      }
      if (hasTotalChunks()) {
        hash = (37 * hash) + TOTAL_CHUNKS_FIELD_NUMBER;
        hash = (53 * hash) + getTotalChunks();
      }
      if (getTracingInfoCount() > 0) {
        hash = (37 * hash) + TRACING_INFO_FIELD_NUMBER;
        hash = (53 * hash) + getTracingInfoList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.opennms.core.ipc.grpc.common.SinkMessageProtos.SinkMessageProto parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.opennms.core.ipc.grpc.common.SinkMessageProtos.SinkMessageProto parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.opennms.core.ipc.grpc.common.SinkMessageProtos.SinkMessageProto parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.opennms.core.ipc.grpc.common.SinkMessageProtos.SinkMessageProto parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.opennms.core.ipc.grpc.common.SinkMessageProtos.SinkMessageProto parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.opennms.core.ipc.grpc.common.SinkMessageProtos.SinkMessageProto parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.opennms.core.ipc.grpc.common.SinkMessageProtos.SinkMessageProto parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.opennms.core.ipc.grpc.common.SinkMessageProtos.SinkMessageProto parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.opennms.core.ipc.grpc.common.SinkMessageProtos.SinkMessageProto parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static org.opennms.core.ipc.grpc.common.SinkMessageProtos.SinkMessageProto parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.opennms.core.ipc.grpc.common.SinkMessageProtos.SinkMessageProto parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.opennms.core.ipc.grpc.common.SinkMessageProtos.SinkMessageProto parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.opennms.core.ipc.grpc.common.SinkMessageProtos.SinkMessageProto prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code SinkMessageProto}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:SinkMessageProto)
        org.opennms.core.ipc.grpc.common.SinkMessageProtos.SinkMessageProtoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.opennms.core.ipc.grpc.common.SinkMessageProtos.internal_static_SinkMessageProto_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.opennms.core.ipc.grpc.common.SinkMessageProtos.internal_static_SinkMessageProto_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.opennms.core.ipc.grpc.common.SinkMessageProtos.SinkMessageProto.class, org.opennms.core.ipc.grpc.common.SinkMessageProtos.SinkMessageProto.Builder.class);
      }

      // Construct using org.opennms.core.ipc.grpc.common.SinkMessageProtos.SinkMessageProto.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getTracingInfoFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        messageId_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        content_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        currentChunkNumber_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        totalChunks_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        if (tracingInfoBuilder_ == null) {
          tracingInfo_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000010);
        } else {
          tracingInfoBuilder_.clear();
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.opennms.core.ipc.grpc.common.SinkMessageProtos.internal_static_SinkMessageProto_descriptor;
      }

      @java.lang.Override
      public org.opennms.core.ipc.grpc.common.SinkMessageProtos.SinkMessageProto getDefaultInstanceForType() {
        return org.opennms.core.ipc.grpc.common.SinkMessageProtos.SinkMessageProto.getDefaultInstance();
      }

      @java.lang.Override
      public org.opennms.core.ipc.grpc.common.SinkMessageProtos.SinkMessageProto build() {
        org.opennms.core.ipc.grpc.common.SinkMessageProtos.SinkMessageProto result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public org.opennms.core.ipc.grpc.common.SinkMessageProtos.SinkMessageProto buildPartial() {
        org.opennms.core.ipc.grpc.common.SinkMessageProtos.SinkMessageProto result = new org.opennms.core.ipc.grpc.common.SinkMessageProtos.SinkMessageProto(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.messageId_ = messageId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.content_ = content_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.currentChunkNumber_ = currentChunkNumber_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.totalChunks_ = totalChunks_;
        if (tracingInfoBuilder_ == null) {
          if (((bitField0_ & 0x00000010) == 0x00000010)) {
            tracingInfo_ = java.util.Collections.unmodifiableList(tracingInfo_);
            bitField0_ = (bitField0_ & ~0x00000010);
          }
          result.tracingInfo_ = tracingInfo_;
        } else {
          result.tracingInfo_ = tracingInfoBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.opennms.core.ipc.grpc.common.SinkMessageProtos.SinkMessageProto) {
          return mergeFrom((org.opennms.core.ipc.grpc.common.SinkMessageProtos.SinkMessageProto)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.opennms.core.ipc.grpc.common.SinkMessageProtos.SinkMessageProto other) {
        if (other == org.opennms.core.ipc.grpc.common.SinkMessageProtos.SinkMessageProto.getDefaultInstance()) return this;
        if (other.hasMessageId()) {
          bitField0_ |= 0x00000001;
          messageId_ = other.messageId_;
          onChanged();
        }
        if (other.hasContent()) {
          setContent(other.getContent());
        }
        if (other.hasCurrentChunkNumber()) {
          setCurrentChunkNumber(other.getCurrentChunkNumber());
        }
        if (other.hasTotalChunks()) {
          setTotalChunks(other.getTotalChunks());
        }
        if (tracingInfoBuilder_ == null) {
          if (!other.tracingInfo_.isEmpty()) {
            if (tracingInfo_.isEmpty()) {
              tracingInfo_ = other.tracingInfo_;
              bitField0_ = (bitField0_ & ~0x00000010);
            } else {
              ensureTracingInfoIsMutable();
              tracingInfo_.addAll(other.tracingInfo_);
            }
            onChanged();
          }
        } else {
          if (!other.tracingInfo_.isEmpty()) {
            if (tracingInfoBuilder_.isEmpty()) {
              tracingInfoBuilder_.dispose();
              tracingInfoBuilder_ = null;
              tracingInfo_ = other.tracingInfo_;
              bitField0_ = (bitField0_ & ~0x00000010);
              tracingInfoBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getTracingInfoFieldBuilder() : null;
            } else {
              tracingInfoBuilder_.addAllMessages(other.tracingInfo_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        if (!hasMessageId()) {
          return false;
        }
        if (!hasContent()) {
          return false;
        }
        for (int i = 0; i < getTracingInfoCount(); i++) {
          if (!getTracingInfo(i).isInitialized()) {
            return false;
          }
        }
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.opennms.core.ipc.grpc.common.SinkMessageProtos.SinkMessageProto parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.opennms.core.ipc.grpc.common.SinkMessageProtos.SinkMessageProto) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object messageId_ = "";
      /**
       * <code>required string message_id = 1;</code>
       */
      public boolean hasMessageId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string message_id = 1;</code>
       */
      public java.lang.String getMessageId() {
        java.lang.Object ref = messageId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            messageId_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string message_id = 1;</code>
       */
      public com.google.protobuf.ByteString
          getMessageIdBytes() {
        java.lang.Object ref = messageId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          messageId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string message_id = 1;</code>
       */
      public Builder setMessageId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        messageId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string message_id = 1;</code>
       */
      public Builder clearMessageId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        messageId_ = getDefaultInstance().getMessageId();
        onChanged();
        return this;
      }
      /**
       * <code>required string message_id = 1;</code>
       */
      public Builder setMessageIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        messageId_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString content_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>required bytes content = 2;</code>
       */
      public boolean hasContent() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required bytes content = 2;</code>
       */
      public com.google.protobuf.ByteString getContent() {
        return content_;
      }
      /**
       * <code>required bytes content = 2;</code>
       */
      public Builder setContent(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        content_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bytes content = 2;</code>
       */
      public Builder clearContent() {
        bitField0_ = (bitField0_ & ~0x00000002);
        content_ = getDefaultInstance().getContent();
        onChanged();
        return this;
      }

      private int currentChunkNumber_ ;
      /**
       * <code>optional int32 current_chunk_number = 5;</code>
       */
      public boolean hasCurrentChunkNumber() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional int32 current_chunk_number = 5;</code>
       */
      public int getCurrentChunkNumber() {
        return currentChunkNumber_;
      }
      /**
       * <code>optional int32 current_chunk_number = 5;</code>
       */
      public Builder setCurrentChunkNumber(int value) {
        bitField0_ |= 0x00000004;
        currentChunkNumber_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 current_chunk_number = 5;</code>
       */
      public Builder clearCurrentChunkNumber() {
        bitField0_ = (bitField0_ & ~0x00000004);
        currentChunkNumber_ = 0;
        onChanged();
        return this;
      }

      private int totalChunks_ ;
      /**
       * <code>optional int32 total_chunks = 6;</code>
       */
      public boolean hasTotalChunks() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional int32 total_chunks = 6;</code>
       */
      public int getTotalChunks() {
        return totalChunks_;
      }
      /**
       * <code>optional int32 total_chunks = 6;</code>
       */
      public Builder setTotalChunks(int value) {
        bitField0_ |= 0x00000008;
        totalChunks_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 total_chunks = 6;</code>
       */
      public Builder clearTotalChunks() {
        bitField0_ = (bitField0_ & ~0x00000008);
        totalChunks_ = 0;
        onChanged();
        return this;
      }

      private java.util.List<org.opennms.core.ipc.grpc.common.SinkMessageProtos.TracingInfo> tracingInfo_ =
        java.util.Collections.emptyList();
      private void ensureTracingInfoIsMutable() {
        if (!((bitField0_ & 0x00000010) == 0x00000010)) {
          tracingInfo_ = new java.util.ArrayList<org.opennms.core.ipc.grpc.common.SinkMessageProtos.TracingInfo>(tracingInfo_);
          bitField0_ |= 0x00000010;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          org.opennms.core.ipc.grpc.common.SinkMessageProtos.TracingInfo, org.opennms.core.ipc.grpc.common.SinkMessageProtos.TracingInfo.Builder, org.opennms.core.ipc.grpc.common.SinkMessageProtos.TracingInfoOrBuilder> tracingInfoBuilder_;

      /**
       * <code>repeated .TracingInfo tracing_info = 7;</code>
       */
      public java.util.List<org.opennms.core.ipc.grpc.common.SinkMessageProtos.TracingInfo> getTracingInfoList() {
        if (tracingInfoBuilder_ == null) {
          return java.util.Collections.unmodifiableList(tracingInfo_);
        } else {
          return tracingInfoBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .TracingInfo tracing_info = 7;</code>
       */
      public int getTracingInfoCount() {
        if (tracingInfoBuilder_ == null) {
          return tracingInfo_.size();
        } else {
          return tracingInfoBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .TracingInfo tracing_info = 7;</code>
       */
      public org.opennms.core.ipc.grpc.common.SinkMessageProtos.TracingInfo getTracingInfo(int index) {
        if (tracingInfoBuilder_ == null) {
          return tracingInfo_.get(index);
        } else {
          return tracingInfoBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .TracingInfo tracing_info = 7;</code>
       */
      public Builder setTracingInfo(
          int index, org.opennms.core.ipc.grpc.common.SinkMessageProtos.TracingInfo value) {
        if (tracingInfoBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureTracingInfoIsMutable();
          tracingInfo_.set(index, value);
          onChanged();
        } else {
          tracingInfoBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .TracingInfo tracing_info = 7;</code>
       */
      public Builder setTracingInfo(
          int index, org.opennms.core.ipc.grpc.common.SinkMessageProtos.TracingInfo.Builder builderForValue) {
        if (tracingInfoBuilder_ == null) {
          ensureTracingInfoIsMutable();
          tracingInfo_.set(index, builderForValue.build());
          onChanged();
        } else {
          tracingInfoBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .TracingInfo tracing_info = 7;</code>
       */
      public Builder addTracingInfo(org.opennms.core.ipc.grpc.common.SinkMessageProtos.TracingInfo value) {
        if (tracingInfoBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureTracingInfoIsMutable();
          tracingInfo_.add(value);
          onChanged();
        } else {
          tracingInfoBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .TracingInfo tracing_info = 7;</code>
       */
      public Builder addTracingInfo(
          int index, org.opennms.core.ipc.grpc.common.SinkMessageProtos.TracingInfo value) {
        if (tracingInfoBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureTracingInfoIsMutable();
          tracingInfo_.add(index, value);
          onChanged();
        } else {
          tracingInfoBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .TracingInfo tracing_info = 7;</code>
       */
      public Builder addTracingInfo(
          org.opennms.core.ipc.grpc.common.SinkMessageProtos.TracingInfo.Builder builderForValue) {
        if (tracingInfoBuilder_ == null) {
          ensureTracingInfoIsMutable();
          tracingInfo_.add(builderForValue.build());
          onChanged();
        } else {
          tracingInfoBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .TracingInfo tracing_info = 7;</code>
       */
      public Builder addTracingInfo(
          int index, org.opennms.core.ipc.grpc.common.SinkMessageProtos.TracingInfo.Builder builderForValue) {
        if (tracingInfoBuilder_ == null) {
          ensureTracingInfoIsMutable();
          tracingInfo_.add(index, builderForValue.build());
          onChanged();
        } else {
          tracingInfoBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .TracingInfo tracing_info = 7;</code>
       */
      public Builder addAllTracingInfo(
          java.lang.Iterable<? extends org.opennms.core.ipc.grpc.common.SinkMessageProtos.TracingInfo> values) {
        if (tracingInfoBuilder_ == null) {
          ensureTracingInfoIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, tracingInfo_);
          onChanged();
        } else {
          tracingInfoBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .TracingInfo tracing_info = 7;</code>
       */
      public Builder clearTracingInfo() {
        if (tracingInfoBuilder_ == null) {
          tracingInfo_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000010);
          onChanged();
        } else {
          tracingInfoBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .TracingInfo tracing_info = 7;</code>
       */
      public Builder removeTracingInfo(int index) {
        if (tracingInfoBuilder_ == null) {
          ensureTracingInfoIsMutable();
          tracingInfo_.remove(index);
          onChanged();
        } else {
          tracingInfoBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .TracingInfo tracing_info = 7;</code>
       */
      public org.opennms.core.ipc.grpc.common.SinkMessageProtos.TracingInfo.Builder getTracingInfoBuilder(
          int index) {
        return getTracingInfoFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .TracingInfo tracing_info = 7;</code>
       */
      public org.opennms.core.ipc.grpc.common.SinkMessageProtos.TracingInfoOrBuilder getTracingInfoOrBuilder(
          int index) {
        if (tracingInfoBuilder_ == null) {
          return tracingInfo_.get(index);  } else {
          return tracingInfoBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .TracingInfo tracing_info = 7;</code>
       */
      public java.util.List<? extends org.opennms.core.ipc.grpc.common.SinkMessageProtos.TracingInfoOrBuilder> 
           getTracingInfoOrBuilderList() {
        if (tracingInfoBuilder_ != null) {
          return tracingInfoBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(tracingInfo_);
        }
      }
      /**
       * <code>repeated .TracingInfo tracing_info = 7;</code>
       */
      public org.opennms.core.ipc.grpc.common.SinkMessageProtos.TracingInfo.Builder addTracingInfoBuilder() {
        return getTracingInfoFieldBuilder().addBuilder(
            org.opennms.core.ipc.grpc.common.SinkMessageProtos.TracingInfo.getDefaultInstance());
      }
      /**
       * <code>repeated .TracingInfo tracing_info = 7;</code>
       */
      public org.opennms.core.ipc.grpc.common.SinkMessageProtos.TracingInfo.Builder addTracingInfoBuilder(
          int index) {
        return getTracingInfoFieldBuilder().addBuilder(
            index, org.opennms.core.ipc.grpc.common.SinkMessageProtos.TracingInfo.getDefaultInstance());
      }
      /**
       * <code>repeated .TracingInfo tracing_info = 7;</code>
       */
      public java.util.List<org.opennms.core.ipc.grpc.common.SinkMessageProtos.TracingInfo.Builder> 
           getTracingInfoBuilderList() {
        return getTracingInfoFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          org.opennms.core.ipc.grpc.common.SinkMessageProtos.TracingInfo, org.opennms.core.ipc.grpc.common.SinkMessageProtos.TracingInfo.Builder, org.opennms.core.ipc.grpc.common.SinkMessageProtos.TracingInfoOrBuilder> 
          getTracingInfoFieldBuilder() {
        if (tracingInfoBuilder_ == null) {
          tracingInfoBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              org.opennms.core.ipc.grpc.common.SinkMessageProtos.TracingInfo, org.opennms.core.ipc.grpc.common.SinkMessageProtos.TracingInfo.Builder, org.opennms.core.ipc.grpc.common.SinkMessageProtos.TracingInfoOrBuilder>(
                  tracingInfo_,
                  ((bitField0_ & 0x00000010) == 0x00000010),
                  getParentForChildren(),
                  isClean());
          tracingInfo_ = null;
        }
        return tracingInfoBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:SinkMessageProto)
    }

    // @@protoc_insertion_point(class_scope:SinkMessageProto)
    private static final org.opennms.core.ipc.grpc.common.SinkMessageProtos.SinkMessageProto DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.opennms.core.ipc.grpc.common.SinkMessageProtos.SinkMessageProto();
    }

    public static org.opennms.core.ipc.grpc.common.SinkMessageProtos.SinkMessageProto getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<SinkMessageProto>
        PARSER = new com.google.protobuf.AbstractParser<SinkMessageProto>() {
      @java.lang.Override
      public SinkMessageProto parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new SinkMessageProto(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<SinkMessageProto> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<SinkMessageProto> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public org.opennms.core.ipc.grpc.common.SinkMessageProtos.SinkMessageProto getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_TracingInfo_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_TracingInfo_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SinkMessageProto_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SinkMessageProto_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022sink-message.proto\")\n\013TracingInfo\022\013\n\003k" +
      "ey\030\001 \002(\t\022\r\n\005value\030\002 \002(\t\"\217\001\n\020SinkMessageP" +
      "roto\022\022\n\nmessage_id\030\001 \002(\t\022\017\n\007content\030\002 \002(" +
      "\014\022\034\n\024current_chunk_number\030\005 \001(\005\022\024\n\014total" +
      "_chunks\030\006 \001(\005\022\"\n\014tracing_info\030\007 \003(\0132\014.Tr" +
      "acingInfoB5\n org.opennms.core.ipc.grpc.c" +
      "ommonB\021SinkMessageProtos"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_TracingInfo_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_TracingInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_TracingInfo_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_SinkMessageProto_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_SinkMessageProto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SinkMessageProto_descriptor,
        new java.lang.String[] { "MessageId", "Content", "CurrentChunkNumber", "TotalChunks", "TracingInfo", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
